name: lxqt-build-tools-snap
base: core18
summary:  Build tools for the LXQt desktop environment (unofficial)
description: |
  This package contains the tools that are needed by the LXQt build process.
  This is the unofficial snap packaging.
  Upstream: https://github.com/lxqt/lxqt-build-tools

grade: stable
confinement: strict

adopt-info: lxqt-build-tools
parts:
  lxqt-build-tools:
    source: https://github.com/lxqt/lxqt-build-tools.git
    source-type: git
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr

    override-pull: |
      snapcraftctl pull
      c1=`git log --oneline -n 1`
      cd $SNAPCRAFT_PROJECT_DIR
      c2=`git log --oneline -n 1`
      d=`date +%y%m%d`
      { t1=${c1#???}; c1=${c1%$t1}; }
      { t2=${c2#???}; c2=${c2%$t2}; }
      ver="$d.$SNAP_ARCH-$c1.$c2"
      echo "Set version: $ver"
      snapcraftctl set-version $ver

    build-packages:
      - libglib2.0-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
